package yagura.view;

import burp.BurpExtender;
import burp.IMessageEditorController;
import burp.IMessageEditorTab;
import burp.IMessageEditorTabFactory;
import extend.view.base.HttpMessage;
import extend.view.base.HttpRequest;
import extend.view.base.HttpResponse;
import extend.util.Util;
import java.awt.Component;
import java.awt.Font;
import java.io.UnsupportedEncodingException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author isayan
 */
public class RawViewTab extends javax.swing.JPanel implements IMessageEditorTabFactory, IMessageEditorTab {

    private boolean request = false;

    /**
     * Creates new form RawViewTab
     *
     * @param request
     */
    public RawViewTab(boolean request) {
        this.request = request;
        initComponents();
        customizeComponents();
    }

    private QuickSearchTab quickSearchTab = new QuickSearchTab();

    private void customizeComponents() {
        this.quickSearchTab.setSelectedTextArea(this.txtRaw);
        this.quickSearchTab.getEncodingComboBox().addItemListener(encodingItemStateChanged);
        add(this.quickSearchTab, java.awt.BorderLayout.SOUTH);
    }

    private final java.awt.event.ItemListener encodingItemStateChanged = new java.awt.event.ItemListener() {
        @Override
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            String encoding = quickSearchTab.getSelectedEncoding();
            if (encoding != null) {
                setMessageView(encoding);
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollRaw = new javax.swing.JScrollPane();
        txtRaw = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        txtRaw.setColumns(20);
        txtRaw.setLineWrap(true);
        txtRaw.setRows(5);
        scrollRaw.setViewportView(txtRaw);

        add(scrollRaw, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollRaw;
    private javax.swing.JTextArea txtRaw;
    // End of variables declaration//GEN-END:variables

    public void setMessageFont(Font font) {
        this.txtRaw.setFont(font);
    }

    private HttpMessage message = null;

    public void setMessageView(String encoding) {
        try {
            if (this.message == null) {
                return;
            }
            if (this.message != null) {
                // Raw
                this.txtRaw.setText(Util.decodeMessage(this.message.getMessageBytes(), encoding));
                this.txtRaw.setCaretPosition(0);
                // View                
            } else {
                this.txtRaw.setText("");
            }
            this.quickSearchTab.clearView();
        } catch (Exception ex) {
            Logger.getLogger(RawViewTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public IMessageEditorTab createNewInstance(IMessageEditorController controller, boolean editable) {
        this.txtRaw.setEditable(false);
        return this;
    }

    @Override
    public String getTabCaption() {
        if (this.request) {
            return "JRaw";
        } else {
            return "JRaw";
        }
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    @Override
    public boolean isEnabled(byte[] content, boolean isRequest) {
        if (this.request && isRequest && content != null && content.length > 0) {
            return true;
        } else if (!this.request && !isRequest && content != null && content.length > 0) {
            return true;
        }
        return false;
    }

    @Override
    public void setMessage(byte[] content, boolean isRequest) {
        try {
            BurpExtender extenderImpl = BurpExtender.getInstance();
            String guessCharset = null;
            HttpMessage httpmessage = null;
            if (isRequest) {
                HttpRequest request = HttpRequest.parseHttpRequest(content);
                httpmessage = request;
                guessCharset = request.getGuessCharset();
            } else {
                HttpResponse response = HttpResponse.parseHttpResponse(content);
                httpmessage = response;
                guessCharset = response.getGuessCharset();
            }
            this.message = httpmessage;
            this.quickSearchTab.getEncodingComboBox().removeItemListener(encodingItemStateChanged);
            this.quickSearchTab.renewEncodingList(guessCharset, extenderImpl.getSelectEncodingList());
            this.encodingItemStateChanged.itemStateChanged(null);
            this.quickSearchTab.getEncodingComboBox().addItemListener(encodingItemStateChanged);
        } catch (ParseException ex) {
            Logger.getLogger(RawViewTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public byte[] getMessage() {
        if (this.message != null) {
            return this.message.getMessageBytes();
        } else {
            return new byte[]{};
        }
    }

    @Override
    public boolean isModified() {
        return false;
    }

    @Override
    public byte[] getSelectedData() {
        try {
            String selectText = this.txtRaw.getSelectedText();
            return selectText.getBytes(this.quickSearchTab.getSelectedEncoding());
        } catch (UnsupportedEncodingException ex) {
            return new byte[]{};
        }
    }

    public String getSelectedText() {
        return this.txtRaw.getSelectedText();
    }

    public void clearView() {
        this.quickSearchTab.clearView();
    }

}
