package yagura.view;

import extension.helpers.CertUtil;
import extension.helpers.FileUtil;
import extension.view.base.CustomDialog;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import yagura.model.CertificateItem;

/**
 *
 * @author isayan
 */
public class ImportCertificatetDlg extends CustomDialog {

    private final static Logger logger = Logger.getLogger(ImportCertificatetDlg.class.getName());

    private final static java.util.ResourceBundle BUNDLE = java.util.ResourceBundle.getBundle("yagura/resources/Resource");


    /**
     * Creates new form ImportCertificate
     */
    public ImportCertificatetDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpFormat = new javax.swing.ButtonGroup();
        pnlCertSIelectmport = new javax.swing.JPanel();
        btnStoreTypeJKS = new javax.swing.JToggleButton();
        btnStoreTypePKCS12 = new javax.swing.JToggleButton();
        txtStoreFile = new javax.swing.JTextField();
        btnImport = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtStorePassword = new javax.swing.JTextField();
        pnlApply = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGrpFormat.add(btnStoreTypeJKS);
        btnStoreTypeJKS.setText("JKS");
        btnStoreTypeJKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreTypeJKSActionPerformed(evt);
            }
        });

        btnGrpFormat.add(btnStoreTypePKCS12);
        btnStoreTypePKCS12.setText("PKCS12");

        txtStoreFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStoreFileKeyPressed(evt);
            }
        });

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        lblPassword.setText("Password:");

        javax.swing.GroupLayout pnlCertSIelectmportLayout = new javax.swing.GroupLayout(pnlCertSIelectmport);
        pnlCertSIelectmport.setLayout(pnlCertSIelectmportLayout);
        pnlCertSIelectmportLayout.setHorizontalGroup(
            pnlCertSIelectmportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCertSIelectmportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCertSIelectmportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCertSIelectmportLayout.createSequentialGroup()
                        .addComponent(btnStoreTypeJKS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStoreTypePKCS12))
                    .addGroup(pnlCertSIelectmportLayout.createSequentialGroup()
                        .addComponent(txtStoreFile, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImport))
                    .addComponent(lblPassword)
                    .addComponent(txtStorePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlCertSIelectmportLayout.setVerticalGroup(
            pnlCertSIelectmportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCertSIelectmportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCertSIelectmportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStoreTypeJKS)
                    .addComponent(btnStoreTypePKCS12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCertSIelectmportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStoreFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStorePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCertSIelectmport, java.awt.BorderLayout.CENTER);

        pnlApply.setPreferredSize(new java.awt.Dimension(550, 50));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlApplyLayout = new javax.swing.GroupLayout(pnlApply);
        pnlApply.setLayout(pnlApplyLayout);
        pnlApplyLayout.setHorizontalGroup(
            pnlApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApplyLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlApplyLayout.setVerticalGroup(
            pnlApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlApplyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(pnlApply, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customizeComponents() {
        this.btnStoreTypePKCS12.setSelected(true);
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setModalResult(JOptionPane.CANCEL_OPTION);
        this.closeDialog(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        CertUtil.StoreType storeType = getStoreType();
        String storePassword = this.txtStorePassword.getText();

        File storeFile = getStoreFile();
        if (!storeFile.exists()) {
            JOptionPane.showMessageDialog(this, BUNDLE.getString("view.certificate.add.certfile.notfound"), "Certificate", JOptionPane.INFORMATION_MESSAGE);
        } else if (!CertUtil.validKeyStore(storeFile, storePassword, storeType)) {
            JOptionPane.showMessageDialog(this, BUNDLE.getString("view.certificate.add.certfile.invalid"), "Certificate", JOptionPane.INFORMATION_MESSAGE);
        } else {
            this.setModalResult(JOptionPane.OK_OPTION);
            this.closeDialog(null);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnStoreTypeJKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreTypeJKSActionPerformed

    }//GEN-LAST:event_btnStoreTypeJKSActionPerformed

    private void txtStoreFileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStoreFileKeyPressed

    }//GEN-LAST:event_txtStoreFileKeyPressed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int selected = filechooser.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            this.txtStoreFile.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnImportActionPerformed

    public CertificateItem getProperty() {
        final CertificateItem prop = new CertificateItem();
        try {
            prop.setSelected(true);
            prop.setStoreType(getStoreType());
            prop.setClientCertificate(FileUtil.bytesFromFile(getStoreFile()));
            prop.setClientCertificatePasswd(this.txtStorePassword.getText());
            return prop;
        } catch (IOException ex) {
            return null;
        }
    }

    public File getStoreFile() {
        String storeFile = this.txtStoreFile.getText().trim();
        return new File(storeFile);
    }

    private CertUtil.StoreType getStoreType() {
        CertUtil.StoreType storeType = this.btnStoreTypePKCS12.isSelected() ? CertUtil.StoreType.PKCS12 : CertUtil.StoreType.JKS;
        return storeType;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImportCertificatetDlg dialog = new ImportCertificatetDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrpFormat;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnOK;
    private javax.swing.JToggleButton btnStoreTypeJKS;
    private javax.swing.JToggleButton btnStoreTypePKCS12;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pnlApply;
    private javax.swing.JPanel pnlCertSIelectmport;
    private javax.swing.JTextField txtStoreFile;
    private javax.swing.JTextField txtStorePassword;
    // End of variables declaration//GEN-END:variables

}
