package yagura.view;

import burp.BurpExtension;
import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.http.message.MimeType;
import burp.api.montoya.ui.Selection;
import extend.util.external.ThemeUI;
import extend.util.external.TransUtil;
import extension.burp.IBurpMessageTab;
import extension.helpers.HttpResponseWapper;
import extension.helpers.StringUtil;
import extension.view.base.CaptureItem;
import java.awt.Component;
import java.awt.Font;
import java.awt.SystemColor;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import passive.ast.HtmlAnalyze;
import passive.ast.JavaScriptAnalyze;
import yagura.model.UniversalViewProperty;

/**
 *
 * @author isayan
 */
public class JsCommetViewTab extends javax.swing.JPanel implements IBurpMessageTab {

    private final static Logger logger = Logger.getLogger(JsCommetViewTab.class.getName());

    final PropertyChangeListener propertyListener = new PropertyChangeListener() {
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            ThemeUI.applyStyleTheme(txtJsComment);
        }
    };

    /**
     * Creates new form JsCommetViewTab
     */
    public JsCommetViewTab() {
        initComponents();
        customizeComponents();
    }

    private final QuickSearchTab quickSearchTab = new QuickSearchTab();

    private org.fife.ui.rtextarea.RTextScrollPane scrollJsComment;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea txtJsComment;

    private void customizeComponents() {

        /**
         * * UI design start **
         */
        this.txtJsComment = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        this.scrollJsComment = new org.fife.ui.rtextarea.RTextScrollPane(this.txtJsComment);
        this.txtJsComment.setWrapStyleWord(false);

        this.txtJsComment.setClearWhitespaceLinesEnabled(true);
        this.txtJsComment.setHighlightCurrentLine(true);
        this.txtJsComment.setCurrentLineHighlightColor(SystemColor.textHighlight);
        this.txtJsComment.setBackground(SystemColor.text);
        this.txtJsComment.setEditable(false);
//        scrollURaw.setViewportView(txtURaw);

        add(this.scrollJsComment, java.awt.BorderLayout.CENTER);

        /**
         * * UI design end **
         */
        this.quickSearchTab.setSelectedTextArea(this.txtJsComment);
        this.quickSearchTab.getEncodingComboBox().addItemListener(encodingItemStateChanged);
        this.quickSearchTab.getUniqCheckBox().setVisible(true);
        this.quickSearchTab.getUniqCheckBox().addItemListener(encodingItemStateChanged);

//        this.txtHtmlComment.setEditorKitForContentType("text/html", this.htmlStyleEditorKit);
//        this.txtHtmlComment.setContentType("text/html");
        add(this.quickSearchTab, java.awt.BorderLayout.SOUTH);

        this.propertyListener.propertyChange(null);
        ThemeUI.addPropertyChangeListener(propertyListener);

    }

    private final java.awt.event.ItemListener encodingItemStateChanged = new java.awt.event.ItemListener() {
        @Override
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            String encoding = quickSearchTab.getSelectedEncoding();
            if (encoding != null) {
                setMessageEncoding(encoding);
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setMessageFont(Font font) {
        this.txtJsComment.setFont(font);
    }

    final JavaScriptAnalyze jsAnalyze = new JavaScriptAnalyze(EnumSet.of(JavaScriptAnalyze.AnalyzeOption.JS_COMMENTS));

    private HttpRequestResponse httpRequestResponse;

    public void setMessageEncoding(String encoding) {
        try {
            if (this.httpRequestResponse == null) {
                return;
            }
            final boolean uniq = this.quickSearchTab.getUniqCheckBox().isSelected();
            this.txtJsComment.setText("");
            SwingWorker swText = new SwingWorker<String, Object>() {
                @Override
                protected String doInBackground() throws Exception {
                    publish("...");
                    final boolean uniq = quickSearchTab.getUniqCheckBox().isSelected();
                    List<String> comments = extractComments(httpRequestResponse, encoding);
                    if (uniq) {
                        comments = comments.stream().distinct().toList();
                    }
                    return TransUtil.join("\r\n", comments);
                }

                @Override
                protected void process(List<Object> chunks) {
                    txtJsComment.setText("Heavy Processing" + StringUtil.repeat("...", chunks.size()));
                }

                @Override
                protected void done() {
                    try {
                        txtJsComment.setText(get());
                        txtJsComment.setCaretPosition(0);
                        quickSearchTab.clearViewAndSearch();
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, ex.getMessage(), ex);
                    }
                }
            };
            swText.execute();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    public List<String> extractComments(HttpRequestResponse httpRequestResponse, String encoding) throws UnsupportedEncodingException {
        String body = StringUtil.getStringCharset(httpRequestResponse.response().body().getBytes(), encoding);
        List<String> comments = new ArrayList<>();
        MimeType mimeType = httpRequestResponse.response().inferredMimeType();
        if (mimeType == MimeType.SCRIPT) {
            jsAnalyze.analyze(body);
            for (CaptureItem comment : jsAnalyze.getCommentList()) {
                comments.add(comment.getCaptureValue());
            }
        }
        else if(mimeType == MimeType.HTML || mimeType == MimeType.XML || mimeType == MimeType.IMAGE_SVG_XML) {
            HtmlAnalyze htmlAnalyze = new HtmlAnalyze(body);
            htmlAnalyze.analyze();
            for (CaptureItem script : htmlAnalyze.getScriptList()) {
                jsAnalyze.analyze(script.getCaptureValue());
                for (CaptureItem comment : jsAnalyze.getCommentList()) {
                    comments.add(comment.getCaptureValue());
                }
            }
        }
        return comments;
    }

    public Component getMessageComponent() {
        return this.txtJsComment;
    }

    public String getSelectedText() {
        String selectText = this.txtJsComment.getSelectedText();
        return selectText;
    }

    public void clearView() {
        this.quickSearchTab.clearView();
    }

    /**
     * @return the lineWrap
     */
    public boolean isLineWrap() {
        return this.txtJsComment.getLineWrap();
    }

    /**
     * @param lineWrap the lineWrap to set
     */
    public void setLineWrap(boolean lineWrap) {
        this.txtJsComment.setLineWrap(lineWrap);
    }

    /**
     * @return
     */
    @Override
    public HttpRequestResponse getHttpRequestResponse() {
        return this.httpRequestResponse;
    }

    @Override
    public void setRequestResponse(HttpRequestResponse httpRequestResponse) {
        final BurpExtension extenderImpl = BurpExtension.getInstance();
        this.httpRequestResponse = httpRequestResponse;
        HttpResponseWapper wrapResponse = new HttpResponseWapper(httpRequestResponse.response());
        String guessCharset = wrapResponse.getGuessCharset(StandardCharsets.UTF_8.name());
        this.quickSearchTab.getEncodingComboBox().removeItemListener(encodingItemStateChanged);
        this.quickSearchTab.renewEncodingList(guessCharset, extenderImpl.getSelectEncodingList());
        encodingItemStateChanged.itemStateChanged(null);
        this.quickSearchTab.getEncodingComboBox().addItemListener(encodingItemStateChanged);
    }

    @Override
    public boolean isEnabledFor(HttpRequestResponse httpRequestResponse) {
        final BurpExtension extenderImpl = BurpExtension.getInstance();
        if (httpRequestResponse == null) {
            return false;
        }
        try {
            HttpResponseWapper wrapResponse = new HttpResponseWapper(httpRequestResponse.response());
            if (!wrapResponse.hasHttpResponse()) {
                return false;
            }
            UniversalViewProperty viewProperty = extenderImpl.getProperty().getUniversalViewProperty();
            EnumSet<UniversalViewProperty.MessageView> view = viewProperty.getMessageView();
            this.setLineWrap(viewProperty.isLineWrap());
            if (!view.contains(UniversalViewProperty.MessageView.JS_COMMENT)) {
                return false;
            }

            // Burp v2023.4.1 以降の謎挙動に対応
            if ((httpRequestResponse.request() != null && httpRequestResponse.request().toByteArray().length() == 0 && httpRequestResponse.response() == null)
                    || (httpRequestResponse.response() != null && httpRequestResponse.response().toByteArray().length() == 0)) {
                return true;
            }
            final boolean uniq = quickSearchTab.getUniqCheckBox().isSelected();
            String encoding = quickSearchTab.getSelectedEncoding();
            if (encoding != null) {
                List<String> comments = extractComments(httpRequestResponse, encoding);
                if (uniq) {
                    comments = comments.stream().distinct().toList();
                }
                return !comments.isEmpty();
            }
            return false;
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
            return false;
        }
    }

    @Override
    public String caption() {
        return "Js Comment";
    }

    @Override
    public Component uiComponent() {
        return this;
    }

    @Override
    public Selection selectedData() {
        return null;
    }

    @Override
    public boolean isModified() {
        return false;
    }

}
