package yagura.view;

import com.google.gson.JsonSyntaxException;
import java.awt.Component;
import java.util.logging.Logger;
import extension.burp.IBurpTab;
import java.security.SignatureException;
import java.util.Comparator;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import passive.JWSToken;

/**
 *
 * @author isayan
 */
public class JWSEncoderTab extends javax.swing.JPanel implements IBurpTab {

    private final static Logger logger = Logger.getLogger(JWSEncoderTab.class.getName());

    private final static java.util.ResourceBundle BUNDLE = java.util.ResourceBundle.getBundle("yagura/resources/Resource");

    private final JWSToken jwsInstance = new JWSToken();

    /**
     * Creates new form JWTWeakTokenScan
     */
    public JWSEncoderTab() {
        initComponents();
        customizeComponents();
    }

    private final String SELECT_ALGO = "Select algorithm";

    private final DefaultComboBoxModel modelAlgo = new DefaultComboBoxModel();

    private final JWSEditPanel panelJWSEdit = new JWSEditPanel();

    private void customizeComponents() {
        this.txtJsonToken.setEditable(false);
        this.modelAlgo.addElement(SELECT_ALGO);

        Set<JWSToken.Algorithm> alogs = JWSToken.getSupportAlgorithm();
        for (JWSToken.Algorithm algo : alogs) {
            this.modelAlgo.addElement(algo);
        }
        this.cmbAlgo.setModel(this.modelAlgo);
        this.pnlToken.add(this.panelJWSEdit, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJTokenDecoder = new javax.swing.JPanel();
        pnlAction = new javax.swing.JPanel();
        cmbAlgo = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        lblTokenValid = new javax.swing.JLabel();
        btnEncode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJsonToken = new javax.swing.JTextArea();
        pnlToken = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlJTokenDecoder.setPreferredSize(new java.awt.Dimension(200, 125));
        pnlJTokenDecoder.setLayout(new java.awt.BorderLayout());

        pnlAction.setPreferredSize(new java.awt.Dimension(125, 125));

        cmbAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblTokenValid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTokenValid.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnEncode.setText("Encode");
        btnEncode.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActionLayout = new javax.swing.GroupLayout(pnlAction);
        pnlAction.setLayout(pnlActionLayout);
        pnlActionLayout.setHorizontalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAlgo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncode, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTokenValid, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlActionLayout.setVerticalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTokenValid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pnlJTokenDecoder.add(pnlAction, java.awt.BorderLayout.LINE_END);

        txtJsonToken.setColumns(20);
        txtJsonToken.setLineWrap(true);
        txtJsonToken.setRows(5);
        jScrollPane1.setViewportView(txtJsonToken);

        pnlJTokenDecoder.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlJTokenDecoder, java.awt.BorderLayout.NORTH);

        pnlToken.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlToken.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlToken.setPreferredSize(new java.awt.Dimension(100, 454));
        pnlToken.setLayout(new java.awt.BorderLayout());
        add(pnlToken, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoActionPerformed
        int index = this.cmbAlgo.getSelectedIndex();
        if (index > 0) {
            if (this.modelAlgo.getSelectedItem() instanceof JWSToken.Algorithm algo) {
                if (this.panelJWSEdit.isValidHeader()) {
                    JWSToken.Header header = this.panelJWSEdit.getHeader();
                    //this.panelJWSEdit.setEnableBase64URL(JWSToken.SYMMETRIC_KEY.contains(header.getAlgorithm()));
                    this.panelJWSEdit.setHeaderText(header.withAlgorithm(algo).toJSON(true));
                }
                else {
                    this.panelJWSEdit.setEnableBase64URL(JWSToken.SYMMETRIC_KEY.contains(algo));
                    //this.panelJWSEdit.setHeaderText(JWSToken.Header.generateAlgorithm(algo).toJSON(true));
                }
            }
        }
    }//GEN-LAST:event_cmbAlgoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.lblTokenValid.setText("");
        this.txtJsonToken.setText("");
        this.panelJWSEdit.clearJWS();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncodeActionPerformed
        try {
            this.lblTokenValid.setText("");
                this.txtJsonToken.setText(this.panelJWSEdit.signToken());
        } catch (JsonSyntaxException ex) {
            this.lblTokenValid.setText(BUNDLE.getString("token.invalid.json"));
        } catch (SignatureException ex) {
            this.lblTokenValid.setText(BUNDLE.getString("token.invalid.token"));
        } catch (java.lang.UnsupportedOperationException ex) {
            this.lblTokenValid.setText(BUNDLE.getString("token.invalid.key"));
        } catch (java.lang.IllegalArgumentException ex) {
            this.lblTokenValid.setText(BUNDLE.getString("token.invalid.key"));
        }
    }//GEN-LAST:event_btnEncodeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEncode;
    private javax.swing.JComboBox<String> cmbAlgo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTokenValid;
    private javax.swing.JPanel pnlAction;
    private javax.swing.JPanel pnlJTokenDecoder;
    private javax.swing.JPanel pnlToken;
    private javax.swing.JTextArea txtJsonToken;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabCaption() {
        return "JWT Encoder";
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    public void setSelectedAlgorithm(JWSToken.Algorithm algo) {
        if (algo == null) {
            this.cmbAlgo.setSelectedIndex(0);
        }
        else {
            this.cmbAlgo.setSelectedItem(algo);
        }
    }
    public JWSToken.Algorithm getSelectedAlgorithm() {
        return (JWSToken.Algorithm)this.cmbAlgo.getSelectedItem();
    }

    public JWSToken.Header getHeader() {
        return this.panelJWSEdit.getHeader();
    }

    public String getHeaderJSON(boolean pretty) {
        return this.panelJWSEdit.getHeaderJSON(pretty);
    }

    public void setHeaderJSON(String value, boolean pretty) {
        this.panelJWSEdit.setHeaderJSON(value, pretty);
    }

    public JWSToken.Payload Payload() {
        return this.panelJWSEdit.getPayload();
    }

    public String getPayloadJSON(boolean pretty) {
        return this.panelJWSEdit.getPayloadJSON(pretty);
    }

    public void setPayloadJSON(String value, boolean pretty) {
        this.panelJWSEdit.setPayloadJSON(value, pretty);
    }

    public String getSecretKey() {
        return this.panelJWSEdit.getSecretKeyText();
    }

    public void setSecretKey(String value) {
        this.panelJWSEdit.setSecretKey(value);
    }

}
