package yagura.view;

import extension.burp.IBurpTab;
import extension.helpers.StringUtil;
import extension.view.base.CustomListModel;
import java.awt.Component;
import javax.swing.DefaultListModel;

/**
 *
 * @author isayan
 */
public class MenuAssignTab extends javax.swing.JPanel implements IBurpTab {

    /**
     * Creates new form MenuAssign
     */
    public MenuAssignTab() {
        initComponents();
        customizeComponents();
    }

    private final CustomListModel<String> modelTarget = new CustomListModel<>();
    private final CustomListModel<String> modelSelect = new CustomListModel<>();

    @SuppressWarnings("unchecked")
    private void customizeComponents() {

        this.listTarget.setModel(this.modelTarget);
        for (String item : StringUtil.getAvailableEncodingList()) {
            if (!modelSelect.contains(item)) {
                this.modelTarget.addElement(item);
            }
        }
        this.listSelect.setModel(this.modelSelect);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTarget = new javax.swing.JLabel();
        scrollTarget = new javax.swing.JScrollPane();
        listTarget = new javax.swing.JList();
        btnEncRightArraw = new javax.swing.JButton();
        btnEncLerftArraw = new javax.swing.JButton();
        scrollSelect = new javax.swing.JScrollPane();
        listSelect = new javax.swing.JList();
        lblSelect = new javax.swing.JLabel();
        pop = new javax.swing.JButton();
        btnEncDownArraw = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encoder", "Decoder", "Converter", "Hash" }));

        lblTarget.setText("Target:");

        listTarget.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scrollTarget.setViewportView(listTarget);

        btnEncRightArraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_right.png"))); // NOI18N
        btnEncRightArraw.addActionListener(this::btnEncRightArrawActionPerformed);

        btnEncLerftArraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_left.png"))); // NOI18N
        btnEncLerftArraw.addActionListener(this::btnEncLerftArrawActionPerformed);

        listSelect.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listSelect.addListSelectionListener(this::listSelectValueChanged);
        scrollSelect.setViewportView(listSelect);

        lblSelect.setText("Select:");

        pop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_up.png"))); // NOI18N
        pop.setText("up");
        pop.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        pop.addActionListener(this::popActionPerformed);

        btnEncDownArraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_down.png"))); // NOI18N
        btnEncDownArraw.setText("down");
        btnEncDownArraw.setHideActionText(true);
        btnEncDownArraw.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEncDownArraw.addActionListener(this::btnEncDownArrawActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEncRightArraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEncLerftArraw, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTarget)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelect)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEncDownArraw))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTarget)
                            .addComponent(lblSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(scrollSelect))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pop)
                                .addGap(18, 18, 18)
                                .addComponent(btnEncDownArraw)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEncRightArraw)
                                .addGap(18, 18, 18)
                                .addComponent(btnEncLerftArraw)
                                .addGap(187, 187, 187))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void moveItemList(javax.swing.JList srcList, javax.swing.JList dstList) {
        DefaultListModel<String> modelSrc = (DefaultListModel<String>) srcList.getModel();
        DefaultListModel<String> modelDst = (DefaultListModel<String>) dstList.getModel();
        int[] indexs = srcList.getSelectedIndices();
        for (int index : indexs) {
            modelDst.addElement(modelSrc.getElementAt(index));
        }
        for (int index = indexs.length; index > 0; index--) {
            modelSrc.removeElementAt(indexs[index - 1]);
        }
    }

    private void btnEncRightArrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncRightArrawActionPerformed
        this.moveItemList(this.listTarget, this.listSelect);
    }//GEN-LAST:event_btnEncRightArrawActionPerformed

    private void btnEncLerftArrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncLerftArrawActionPerformed
        this.moveItemList(this.listSelect, this.listTarget);
    }//GEN-LAST:event_btnEncLerftArrawActionPerformed

    private void listSelectValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSelectValueChanged
        if (evt.getSource() instanceof javax.swing.JList list) {
            String selectValue = String.valueOf(list.getSelectedValue());
        }
    }//GEN-LAST:event_listSelectValueChanged

    private void popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popActionPerformed
        int index = this.modelSelect.moveUp(this.listSelect.getSelectedIndex());
        this.listSelect.setSelectedIndex(index);
    }//GEN-LAST:event_popActionPerformed

    private void btnEncDownArrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncDownArrawActionPerformed
        int index = this.modelSelect.moveDown(this.listSelect.getSelectedIndex());
        this.listSelect.setSelectedIndex(index);
    }//GEN-LAST:event_btnEncDownArrawActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncDownArraw;
    private javax.swing.JButton btnEncLerftArraw;
    private javax.swing.JButton btnEncRightArraw;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JList listSelect;
    private javax.swing.JList listTarget;
    private javax.swing.JButton pop;
    private javax.swing.JScrollPane scrollSelect;
    private javax.swing.JScrollPane scrollTarget;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabCaption() {
        return "Yagura Menu";
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

}
