/*
 * SendToTab.java
 *
 * Created on 2010/11/27, 13:21:00
 */
package yagura.view;

import extension.view.base.TableRowTransferHandler;
import extension.helpers.SwingUtil;
import extension.view.base.CustomTableModel;
import yagura.model.SendToItem;
import yagura.model.SendToProperty;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DropMode;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import extension.burp.IBurpTab;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author isayan
 */
public class SendToTab extends javax.swing.JPanel implements IBurpTab {

    private final static Logger logger = Logger.getLogger(SendToTab.class.getName());

    /**
     * Creates new form SendToTab
     */
    public SendToTab() {
        initComponents();
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabSendTo = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        btnSendToEdit = new javax.swing.JButton();
        btnSendToRemove = new javax.swing.JButton();
        btnSendToAdd = new javax.swing.JButton();
        btnSendToDownArraw = new javax.swing.JButton();
        btnSendToUpArraw = new javax.swing.JButton();
        chkSubmenu = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSendTo = new javax.swing.JTable();
        chkForceSortOrder = new javax.swing.JCheckBox();
        btnSendToDuplicate = new javax.swing.JButton();
        lblMenuPlace = new javax.swing.JLabel();
        cmbPlaceLevel = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(550, 450));
        setLayout(new java.awt.BorderLayout());

        tabSendTo.setPreferredSize(new java.awt.Dimension(550, 300));
        tabSendTo.setLayout(new java.awt.BorderLayout());

        btnSendToEdit.setText("Edit");
        btnSendToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToEditActionPerformed(evt);
            }
        });

        btnSendToRemove.setText("Remove");
        btnSendToRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToRemoveActionPerformed(evt);
            }
        });

        btnSendToAdd.setText("Add");
        btnSendToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToAddActionPerformed(evt);
            }
        });

        btnSendToDownArraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_down.png"))); // NOI18N
        btnSendToDownArraw.setText("down");
        btnSendToDownArraw.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSendToDownArraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToDownArrawActionPerformed(evt);
            }
        });

        btnSendToUpArraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yagura/resources/arrow_up.png"))); // NOI18N
        btnSendToUpArraw.setText("up");
        btnSendToUpArraw.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSendToUpArraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToUpArrawActionPerformed(evt);
            }
        });

        chkSubmenu.setText("Send To Submenu");
        chkSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSubmenuActionPerformed(evt);
            }
        });

        tableSendTo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "select", "MenuCaption", "Server", "Target", "Req Header", "Req Body", "Res Header", "Res Body", "Rev Order", "ExtendProp", "Extend", "HotKey"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSendTo.getTableHeader().setReorderingAllowed(false);
        tableSendTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableSendToKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableSendTo);
        if (tableSendTo.getColumnModel().getColumnCount() > 0) {
            tableSendTo.getColumnModel().getColumn(0).setResizable(false);
            tableSendTo.getColumnModel().getColumn(7).setResizable(false);
            tableSendTo.getColumnModel().getColumn(8).setResizable(false);
            tableSendTo.getColumnModel().getColumn(9).setResizable(false);
            tableSendTo.getColumnModel().getColumn(10).setResizable(false);
            tableSendTo.getColumnModel().getColumn(11).setResizable(false);
        }

        chkForceSortOrder.setText("Force sort order");
        chkForceSortOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkForceSortOrderActionPerformed(evt);
            }
        });

        btnSendToDuplicate.setText("Duplicate");
        btnSendToDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToDuplicateActionPerformed(evt);
            }
        });

        lblMenuPlace.setText("Menu Place:");

        cmbPlaceLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlaceLevelItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSendToEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSendToRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSendToDuplicate, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(btnSendToAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendToDownArraw, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendToUpArraw, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuPlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPlaceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSubmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkForceSortOrder)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuPlace)
                    .addComponent(cmbPlaceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSubmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkForceSortOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(btnSendToEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendToRemove)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendToUpArraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendToDownArraw)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendToAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendToDuplicate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSendTo.add(pnlCenter, java.awt.BorderLayout.PAGE_START);

        add(tabSendTo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getTabCaption() {
        return "SendTo";
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    private CustomTableModel modelSendTo = null;

    private final SendToItemDlg sendtoItemDlg = new SendToItemDlg(null, true);

//    private final TransferHandler handler = new TableRowTransferHandler();

    @SuppressWarnings("unchecked")
    private void customizeComponents() {

        // SendTo Tab
        this.cmbPlaceLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { SendToProperty.SendToMenuPlace.DEFAULT.toIdent(), SendToProperty.SendToMenuPlace.TOP_LEVEL.toIdent()}));
        this.modelSendTo = new CustomTableModel(this.tableSendTo.getModel());
        this.tableSendTo.setModel(this.modelSendTo);

        this.btnSendToEdit.setEnabled(this.tableSendTo.getSelectedRowCount() > 0);
        this.btnSendToDuplicate.setEnabled(this.tableSendTo.getSelectedRowCount() > 0);
        this.btnSendToRemove.setEnabled(this.tableSendTo.getSelectedRowCount() > 0);
        this.modelSendTo.addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {
                firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, getSendToProperty());
            }
        });

        this.tableSendTo.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }
                int rowCount = tableSendTo.getSelectedRowCount();
                btnSendToEdit.setEnabled((rowCount > 0));
                btnSendToDuplicate.setEnabled((rowCount > 0));
                btnSendToRemove.setEnabled((rowCount > 0));
            }
        });

        this.tableSendTo.setDragEnabled(true);
        this.tableSendTo.setDropMode(DropMode.INSERT_ROWS);
        this.tableSendTo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        this.tableSendTo.setTransferHandler(new TableRowTransferHandler());
        this.tableSendTo.setFillsViewportHeight(true);

        // selected
        this.tableSendTo.getColumnModel().getColumn(0).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.tableSendTo.getColumnModel().getColumn(0).setMaxWidth(30);

        // Caption
        this.tableSendTo.getColumnModel().getColumn(1).setMinWidth(80);
        this.tableSendTo.getColumnModel().getColumn(1).setPreferredWidth(150);
        this.tableSendTo.getColumnModel().getColumn(1).setMaxWidth(300);

        // server
        this.tableSendTo.getColumnModel().getColumn(2).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(2).setPreferredWidth(30);
        this.tableSendTo.getColumnModel().getColumn(2).setMaxWidth(40);

        // Target
        this.tableSendTo.getColumnModel().getColumn(3).setMinWidth(80);
        this.tableSendTo.getColumnModel().getColumn(3).setPreferredWidth(200);
        this.tableSendTo.getColumnModel().getColumn(3).setMaxWidth(800);

        // request header
        this.tableSendTo.getColumnModel().getColumn(4).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(4).setPreferredWidth(50);
        this.tableSendTo.getColumnModel().getColumn(4).setMaxWidth(120);

        // request body
        this.tableSendTo.getColumnModel().getColumn(5).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(5).setPreferredWidth(50);
        this.tableSendTo.getColumnModel().getColumn(5).setMaxWidth(120);

        // response header
        this.tableSendTo.getColumnModel().getColumn(6).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(6).setPreferredWidth(50);
        this.tableSendTo.getColumnModel().getColumn(6).setMaxWidth(120);

        // response body
        this.tableSendTo.getColumnModel().getColumn(7).setMinWidth(20);
        this.tableSendTo.getColumnModel().getColumn(7).setPreferredWidth(50);
        this.tableSendTo.getColumnModel().getColumn(7).setMaxWidth(120);

        // reverse order
        this.tableSendTo.getColumnModel().getColumn(8).setMinWidth(0);
        this.tableSendTo.getColumnModel().getColumn(8).setPreferredWidth(0);
        this.tableSendTo.getColumnModel().getColumn(8).setMaxWidth(0);

        // ExendProperty
        this.tableSendTo.getColumnModel().getColumn(9).setMinWidth(0);
//        this.tableSendTo.getColumnModel().getColumn(9).setPreferredWidth(80);
        this.tableSendTo.getColumnModel().getColumn(9).setMaxWidth(0);

        // Extend
        this.tableSendTo.getColumnModel().getColumn(10).setMinWidth(0);
        this.tableSendTo.getColumnModel().getColumn(10).setPreferredWidth(0);
        this.tableSendTo.getColumnModel().getColumn(10).setMaxWidth(0);

        // HotKey
        this.tableSendTo.getColumnModel().getColumn(11).setMinWidth(0);
        this.tableSendTo.getColumnModel().getColumn(11).setPreferredWidth(0);
        this.tableSendTo.getColumnModel().getColumn(11).setMaxWidth(0);

    }

    private void btnSendToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToEditActionPerformed
        this.showSendToItemDlg(true);
        //this.firePropertyChange(TabbetOption.SENDTO_PROPERTY, null, this.getSendToProperty());
}//GEN-LAST:event_btnSendToEditActionPerformed

    private void btnSendToRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToRemoveActionPerformed
        SwingUtil.removeItem(this.tableSendTo);
        //this.firePropertyChange(TabbetOption.SENDTO_PROPERTY, null, this.getSendToProperty());
}//GEN-LAST:event_btnSendToRemoveActionPerformed

    private void btnSendToUpArrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToUpArrawActionPerformed
        int index = this.tableSendTo.getSelectedRow();
        index = this.modelSendTo.moveUp(index);
        this.tableSendTo.getSelectionModel().setSelectionInterval(index, index);
        this.firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, this.getSendToProperty());
}//GEN-LAST:event_btnSendToUpArrawActionPerformed

    private void btnSendToDownArrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToDownArrawActionPerformed
        int index = this.tableSendTo.getSelectedRow();
        index = this.modelSendTo.moveDn(index);
        this.tableSendTo.getSelectionModel().setSelectionInterval(index, index);
        this.firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, this.getSendToProperty());
}//GEN-LAST:event_btnSendToDownArrawActionPerformed

    private void btnSendToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToAddActionPerformed
        this.showSendToItemDlg(false);
}//GEN-LAST:event_btnSendToAddActionPerformed

    private void chkSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSubmenuActionPerformed
        this.firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, this.getSendToProperty());
    }//GEN-LAST:event_chkSubmenuActionPerformed

    private void tableSendToKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableSendToKeyPressed
    }//GEN-LAST:event_tableSendToKeyPressed

    private void chkForceSortOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkForceSortOrderActionPerformed
        this.firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, this.getSendToProperty());
    }//GEN-LAST:event_chkForceSortOrderActionPerformed

    private void btnSendToDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToDuplicateActionPerformed
        this.sendtoItemDlg.setLocationRelativeTo(this);
        this.sendtoItemDlg.setItemList(this.getSendToItemList());
        this.sendtoItemDlg.setItem(getEditItem());
        this.sendtoItemDlg.setVisible(true);
        if (this.sendtoItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
            SendToItem item = this.sendtoItemDlg.getItem();
            setEditItem(item, false);
        }
    }//GEN-LAST:event_btnSendToDuplicateActionPerformed

    private void cmbPlaceLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlaceLevelItemStateChanged
        this.firePropertyChange(SendToProperty.SENDTO_PROPERTY, null, this.getSendToProperty());
    }//GEN-LAST:event_cmbPlaceLevelItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendToAdd;
    private javax.swing.JButton btnSendToDownArraw;
    private javax.swing.JButton btnSendToDuplicate;
    private javax.swing.JButton btnSendToEdit;
    private javax.swing.JButton btnSendToRemove;
    private javax.swing.JButton btnSendToUpArraw;
    private javax.swing.JCheckBox chkForceSortOrder;
    private javax.swing.JCheckBox chkSubmenu;
    private javax.swing.JComboBox<String> cmbPlaceLevel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenuPlace;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel tabSendTo;
    private javax.swing.JTable tableSendTo;
    // End of variables declaration//GEN-END:variables

    public void setSendToItemList(List<SendToItem> list) {
        if (list == null) {
        } else {
            this.modelSendTo.beginUpdate();
            this.modelSendTo.removeAll();
            for (int i = 0; i < list.size(); i++) {
                SendToItem sendToItem = list.get(i);
                Object editRows[] = SendToItem.toObjects(sendToItem);
                this.modelSendTo.addRow(editRows);
            }
            this.modelSendTo.endUpdate();
        }
    }

    public List<SendToItem> getSendToItemList() {
        javax.swing.JTable srcTable = this.tableSendTo;
        List<SendToItem> list = new ArrayList<>();
        for (int i = 0; i < srcTable.getRowCount(); i++) {
            Object editRows[] = this.modelSendTo.getRows(i);
            list.add(SendToItem.fromObjects(editRows));
        }
        return list;
    }

    private SendToItem getEditItem() {
        SendToItem item = new SendToItem();
        Object editCols[] = SwingUtil.editItem(this.tableSendTo);
        if (editCols != null) {
            item = SendToItem.fromObjects(editCols);
        }
        return item;
    }

    private void setEditItem(SendToItem item, boolean update) {
        Object[] rows = SendToItem.toObjects(item);
        SwingUtil.addOrUpdateItem(this.tableSendTo, rows, update);
    }

    @SuppressWarnings("unchecked")
    private void showSendToItemDlg(boolean editMode) {
        this.sendtoItemDlg.setLocationRelativeTo(this);
        this.sendtoItemDlg.setItemList(this.getSendToItemList());
        if (editMode) {
            this.sendtoItemDlg.setItem(getEditItem());
        } else {
            SendToItem item = new SendToItem();
            this.sendtoItemDlg.setItem(item);
        }
        this.sendtoItemDlg.setVisible(true);
        if (this.sendtoItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
            SendToItem item = this.sendtoItemDlg.getItem();
            setEditItem(item, editMode);
        }
    }

    public void setSendToProperty(SendToProperty sendToProperty) {
        this.setSendToItemList(sendToProperty.getSendToItemList());
        this.cmbPlaceLevel.setSelectedItem(sendToProperty.getMenuPlace().toIdent());
        this.chkSubmenu.setSelected(sendToProperty.isSubMenu());
        this.chkForceSortOrder.setSelected(sendToProperty.isForceSortOrder());
    }

    public SendToProperty getSendToProperty() {
        SendToProperty sendToProperty = new SendToProperty();
        sendToProperty.setMenuPlace(SendToProperty.SendToMenuPlace.parseEnumIdent((String)this.cmbPlaceLevel.getSelectedItem()));
        sendToProperty.setSendToItemList(this.getSendToItemList());
        sendToProperty.setSubMenu(this.chkSubmenu.isSelected());
        sendToProperty.setForceSortOrder(this.chkForceSortOrder.isSelected());
        return sendToProperty;
    }

    public static void main(String [] args) {
        EventQueue.invokeLater(MainPanel::createAndShowGui);
    }

    final static class MainPanel extends JPanel {

        private MainPanel() {
            super(new BorderLayout());
            SendToTab sendTo = new SendToTab();
            java.util.List<SendToItem> list = new ArrayList<>();
            SendToItem item1 = new SendToItem();
            item1.setCaption("caption1");
            item1.setTarget("target1");
            item1.setExtend(SendToItem.ExtendType.SEND_TO_JTRANSCODER);
            list.add(item1);
            SendToItem item2 = new SendToItem();
            item2.setCaption("caption2");
            item2.setTarget("target2");
            list.add(item2);
            SendToItem item3 = new SendToItem();
            item3.setCaption("caption3");
            item3.setTarget("target3");
            list.add(item3);
            sendTo.setSendToItemList(list);
            this.add(sendTo, BorderLayout.CENTER);
            setPreferredSize(new Dimension(800, 600));
        }

        private static void createAndShowGui() {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (UnsupportedLookAndFeelException ignored) {
                Toolkit.getDefaultToolkit().beep();
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                ex.printStackTrace();
                return;
            }
            JFrame frame = new JFrame("DnDTable");
            frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            frame.getContentPane().add(new MainPanel());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }


}
